### ISSUE TITLE
Locale detected incorrectly

### ISSUE THREAD

**Issue by dkBrazz** [translate/virtaal#3224]
I have Win10 with English UI and Ukrainian Locale (time/date, currency etc.)
But Virtaal shows Ukrainian UI
It looks like the Virtaal reads locale for UI in wrong place

```
C:\>wmic.exe os get locale, oslanguage
Locale  OSLanguage
0422    1033
```
Locale = 0422 (hex) - uk-UA 	Ukrainian - Ukraine
OSLanguage = 1033 (dec, 0409 in hex) - en-US 	English - United States

For UI language in Windows should be used OSLanguage, not System Locale

**Comment by friedelwolff** [comment]
If I remember correctly, the issue was that Virtaal is translated into languages that don't have Windows localisations, and going by the system locale would make it close to impossible to even run it with the localised UI. The unavailability of most languages early in a Windows version's life, means that someone upgrading will have to fall back to English (or similar) until their language interface pack is available (even in the case where the language is supported by Windows). Language interface packs are also hard to install compared to Linux systems where UI localisation is usually available from installation time.

Going by the locale is the norm on Linux, so I guess it is done in that spirit. I guess a case could have been made either way, but these were the reasons if I remember correctly.

**Comment by friedelwolff** [comment]
If you want to override this behaviour, you can edit the virtaal.ini file and set the "uilang" to "en" under the [language] section.

**Comment by dkBrazz** [comment]
Things you say don't relate to my problem
My Windows is configured for English UI, all Windows applications detects right UI language and shows english UI
And of course, my Windows has English localization

But Virtaal looks into System Locale which should be used only for date/time, currency localizations, and shouldn't for UI.

And it is a bug

Overriding locale in ini file is just workaround for this bug.

**Comment by dkBrazz** [comment]
The differences between Locales and Languages in windows described in this article - http://blogs.msdn.com/b/heaths/archive/2005/02/17/375830.aspx

**Comment by dkBrazz** [comment]
https://github.com/translate/virtaal/blob/master/virtaal/support/libi18n/locale.py#L277 - 
```python
def get_win32_lang(system_ui=False):
...
    if system_ui:
        #Windows UI language
        langid = windll.kernel32.GetUserDefaultUILanguage()
    else:
        #User's locale
        langid = windll.kernel32.GetUserDefaultLangID()
```

And **system_ui** is always false

GetUserDefaultUILanguage() - https://msdn.microsoft.com/en-us/library/windows/desktop/dd318137%28v=vs.85%29.aspx
Returns the language identifier for the user **UI language** for the current user.

GetUserDefaultLangID() - https://msdn.microsoft.com/en-us/library/windows/desktop/dd318134%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
Returns the language identifier of the **Region Format** setting for the current user.

Just put **true** into **get_win32_lang**
