### ISSUE TITLE
Guide comments are in english

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3232]
I have translated virtaal to my language but if you start the guide the comments are still in english.

Like this first comment where you have to translate "Welcome" to your language:
> Welcome to the Virtaal tutorial. You can do the first translation by typing just the translation for "Welcome". Then press Enter.

**Comment by unho** [comment]
Are you using latest master? Do you have the MO file compiled and in place?

**Comment by scootergrisen** [comment]
I am using latest MO file but i guess it might be because i'm not using the latest master.
I'm just using the latest stable 0.7.1.
I'm not good at building programs.
I allways have problems with installing dependencies, the system will not allow me to install some versions and stuff like that.

**Comment by unho** [comment]
The tutorial (I am guessing that that is what you call guide) is only localizable on master. Latest stable Virtaal only offers a tutorial in English.

**Comment by friedelwolff** [comment]
Thanks to Leandro's work, this exact feature was implemented since version 0.7.1 was released. We'll have a beta version available soon, and then (with a full translation) it should have translated instructions/comments. I'm closing this issue, but feel free to reopen if there are problems when you test it then.

**Comment by scootergrisen** [comment]
Ok waiting for the new release.
