### ISSUE TITLE
Double words in english strings

### ISSUE THREAD

**Issue by scootergrisen** [translate/virtaal#3235]
I noticed some mistakes in the english text while translating:

"to to":

> 	An accelerator key is a key on your keyboard that you can press to to quickly

"to to":

> 	This message contains a large number that is formatted according to to American

"on on":

> 	This message contains a link that the user will be able to click on on to

**Comment by friedelwolff** [comment]
Thank you for reporting these! This is part of the string review that we still need before string freeze. @unho will you be able to look at these strings in the tutorial?

This is an interesting case for me showing that PEP-8 line lengths can make certain things harder to review. All of these are because of string splitting at 80 columns, and searching for "to to" over the python files does not show where this is happening. (Not that I think there is an easy alternative...)

I also want to do another review of the tutorial strings. If things go well, it might already be today or this week.

**Comment by scootergrisen** [comment]
the the:
msgid ""
"An accelerator key is a key on your keyboard that you can press to to "
"quickly access a menu or function. It is also called a hot key, access key "
"or mnemonic. In program interfaces they are shown as an underlined letter in "
"the text label. In the translatable text they are marked using some "
"character like the underscore here, but other characters are used for this "
"as well. In this case the the accelerator key is \"f\" since the underscore "
"is before this letter and it means that this accelerator could be triggered "
"by pressing Alt+F."

the the:
msgid ""
"In the previous entry you have created one terminology entry for the the "
"\"filter\" verb. Now do the same for \"filter\" noun."
